### ISSUE TITLE
App.config should start from capital A

### ISSUE THREAD

**Issue by oleksii-nimbus** [mrbrl/PCLAppConfig#11]
When I followed instructions for the "FOR FILE SYSTEM APP.CONFIG" section and named file app.config in lowercase, app has thrown exception: config file not found. 

Correct name should be App.config (starting from capital A). 
Please update documentation.

**Comment by soroshsabz** [comment]
ITNOA

@oleksii-nimbus thx I correct in my branch. @mrbrl please correct this problem in main branch. I change it in PR #6.

**Comment by mrbrl** [comment]
thanks @soroshsabz - this is now merged and deployed in a few minutes
