### ISSUE TITLE
Allow this package to be available without Forms dependency

### ISSUE THREAD

**Issue by spontoreau** [mrbrl/PCLAppConfig#12]
Hi how are you ?

The library allows us to initialize ConfigurationManager with a Stream, but it forces developers to have a dependency on Forms, why?

Currently it's impossible to use PCLAppConfig outside of a Forms project, but you can intialize it without an App.config file (i did it with a basic xml file). If you install PCLAppConfig inside a PCL and add the library reference in a Xamarin standard project, it works.

I understand this library is marked as "Forms" compliant, but it can support every platforms, so it will be great for the Forms/App.config support to have an extension package instead of embbed this part inside the main package.

Thanks,
Vtek

**Comment by mrbrl** [comment]
Hey,

Just checking in after a long while.
prepping for .Net standard upgrade.
Re: xamarin.forms: Indeed. Consider it done
