### ISSUE TITLE
The Type Initializer for ConfigurationManager

### ISSUE THREAD

**Issue by carl-neng** [mrbrl/PCLAppConfig#14]
When I have uncoment your sample code : 
![image](https://user-images.githubusercontent.com/22851711/32154780-85b5a4d2-bd65-11e7-9f0c-4f000f475077.png)

I got this bug : 
![image](https://user-images.githubusercontent.com/22851711/32154751-53c63c66-bd65-11e7-9bbe-bea924dd4257.png)

And I want to create three file for app.cofig like:
1 -App.Debug.config
2 -App.Release.config
3 -App.AppStore.config

But I can't create it. so please help me...... thank advances.

**Comment by soroshsabz** [comment]
ITNOA

@carl-neng Hi,

Please follow [for embedded appconfig](https://github.com/mrbrl/PCLAppConfig#for-embedded-appconfig) instructions.
