### ISSUE TITLE
Net Standard Support

### ISSUE THREAD

**Issue by SkyeHoefling** [mrbrl/PCLAppConfig#15]
This is a really cool project but I am unable to get it working on a net standard project. It appears there is no support for it as far as I can tell. Is there any plans to support it in the future or where there issues trying to get this working in net standard

**Comment by soroshsabz** [comment]
ITNOA

Hi,

@ahoefling God willing, It will be supported by next month.

**Comment by Ibcrootbeer** [comment]
Is this still in the works?

**Comment by mrbrl** [comment]
all done
get 0.4.1 at 
https://www.nuget.org/packages/PCLAppConfig
