### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by shidcordero** [mrbrl/PCLAppConfig#16]
This plugin has security issue. When making the App.config as Embedded Resource, the app will build copying the App.config on build time. When doing reverse engineering by for example:

1. Download the apk
2. Change it to .zip
3. Use Reflection and drag the pcl .dll file

It will directly show all your config data, so if  you have client_id and client_secret, it will expose it to hackers.

**Comment by mrbrl** [comment]
indeed, hence better not to put there here.
you can also encrypt your config values and decrypt them at runtime (use securestring and keyvault for extra security) as you go.
or encrypt the whole config file , deploy it as such, decrypt on app start.
