### ISSUE TITLE
Could not load file or assembly 'PCLAppConfig' in UWP project

### ISSUE THREAD

**Issue by MattePozzy** [mrbrl/PCLAppConfig#21]
Hi,
I have a Xamarin project with iOS, Android and UWP projects.
I have installed the version 1.0.1 from nuGet in all three projects and in PCL's one.

The iOS and Android projects works fine but when I run the UWP project this error is triggered:

`**System.IO.FileLoadException**: 'Could not load file or assembly 'PCLAppConfig, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'`

The compile works fine, only at runtime the error come.

How can I solve this error?

**Comment by MattePozzy** [comment]
Hi,
maybe I found the problem but I cannot resolve it.

From nuGet I have installed the latest version, the 1.01 but the version of the DLL is the 0.4.0.

Maybe UWP read the 0.4.0 version and trigger the error?

**Comment by mikejramsey** [comment]
having the same exact problem. installed the latest nuget package in both the Shared project and the UWP project... both are 1.01.  when running i received the same error. 

`The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
`
I have tried downgrading the nuget packages to the 0.4.1 version with no luck either. 

Any suggestions on how to get this working?

**Comment by furystormss** [comment]
I can confirm this issue is due to the 1.01 version conflict with 0.4.0.
I resolved this issue by downgrading all versions (Base+android+ios+uwp) to 0.4.1.
Please fix!

**Comment by soroshsabz** [comment]
ITNOA

@mrbrl Please fix it

**Comment by abrantie1z** [comment]
Please fix this issues for us.

**Comment by abrantie1z** [comment]
I also confirm downgrading the package to 0.4.1 works

**Comment by soroshsabz** [comment]
@abrantie1z I think I can resolved this problem and I create PR #23 so you can test it. from this PR.

**Comment by soroshsabz** [comment]
@abrantie1z @Raystorm7  I add nupkg in [GitHub Actions](https://github.com/soroshsabz/PCLAppConfig/actions/runs/67378334) , so please test it manually to ensure all things is correct.

thanks :)

**Comment by soroshsabz** [comment]
@mrbrl thanks for merge PR #23, please make release to resolve @abrantie1z problem

thanks :)
