### ISSUE TITLE
After forking, can't compile

### ISSUE THREAD

**Issue by ehuna** [mrbrl/PCLAppConfig#4]
Great work guys!

I'm now using PCLAppConfig in one of my projects and one thing I've done is create separate Configuration Solutions to target different environments.  Then I can have separate App.ENVIRONMENT.config files, for each environment.

I wanted to add this support for multiple configuration files per environment back into PCLAppConfig, but after I forked, I can't compile.  

Can you try to clone on a clean environment and fix the compilation issues?

Thanks!

**Comment by mrbrl** [comment]
Good morning ,

Will be looking into it this week. Also, support for multiple config files per env is done but not exposed. I plan to expose this as well as adding a few other features this month.

Thanks,

Ben

**Comment by mrbrl** [comment]
I just did a clean clone, and rebuild for ios , android and uwp target, and i could not encounter any compilation issues.
Did you restore the nuget packages for the solution?
Could you send the compilation errors you are getting?
Thanks

Ben

**Comment by mrbrl** [comment]
no further comments: closing
