### ISSUE TITLE
Android, Error	CS0117: 'Resource.Styleable' does not contain a definition for 'TextInputLayout_hintEnabled'

### ISSUE THREAD

**Issue by ehuna** [mrbrl/PCLAppConfig#5]
Hello,

After adding the PCLAppConfig nuget packages to the PCL and iOS projects, everything works as expected.

On the Android project, I get the following error:

Severity    Code    Description Project File    Line    Suppression State
Error   CS0117  'Resource.Styleable' does not contain a definition for 'TextInputLayout_hintEnabled'    TeslaLogistics.Droid     [MYPROJECTPATH]\Droid\Resources\Resource.designer.cs   1811    Active

This line in Resources/Resource.designer.cs is the issue -

global::PCLAppConfig.FileSystemStream.Android.Resource.Styleable.TextInputLayout_hintEnabled = global::TeslaLogistics.Droid.Resource.Styleable.TextInputLayout_hintEnabled;

and there are 398 errors similar to this one.

If I manually delete the problematic lines, on clean and re-compile the Resources/Resource.designer.cs gets populated again with the 399 errors.

What am I doing wrong?

**Comment by mrbrl** [comment]
can you try to compile the demo app on android target? 
if it compile fine, can you then compare the Xamarin.AndroidSupport.x libraries version on your projects with the ones on the demo app?

Thanks,

Ben

**Comment by mrbrl** [comment]
no further comments: closing
