### ISSUE TITLE
License for NuGet Package is Different than License for Source Code

### ISSUE THREAD

**Issue by dannydwarren** [mrbrl/PCLAppConfig#8]
Source Code is GPLv3
NuGet Package is Apache 2.0

That is incompatible based on licensing.

**Comment by dannydwarren** [comment]
Would prefer this be Apache 2.0 so we can use this in App Store Apps. GPLv3 forces me to open source my Mobile Apps if I distribute in the store.

**Comment by mrbrl** [comment]
Good Point. updated to Apache2

**Comment by dannydwarren** [comment]
AWESOME! Thank you.
