### ISSUE TITLE
error [ConfigurationManager.AppSettings value is null]when run on windows phone

### ISSUE THREAD

**Issue by BleyChen** [mrbrl/PCLAppConfig#9]
Whether this package can't support windows phone ,when i run windows phone project and click "pcl appconfig" button as following:
1.click button
![error0](https://cloud.githubusercontent.com/assets/15098626/22877975/c7af9420-f212-11e6-91dc-7c7a9a27106f.png)
2.throw error
![error](https://cloud.githubusercontent.com/assets/15098626/22877816/20fbc8ec-f212-11e6-9774-fae354410aee.png)

**Comment by soroshsabz** [comment]
ITNOA

Hi,

@BleyChen what is the version of window phone OS? and SDK?
and what is the version of PCLAppConfig?

**Comment by mrbrl** [comment]
we are deprecating windows phone. uwp stands strong
